### ISSUE TITLE
Backoff between retries

### ISSUE THREAD

**Issue by rclark** [sindresorhus/p-retry#1]
It would be nice to be able to retry async requests with backoff that grows based on the number of times the request has failed. For example here's a case where you'd delay the retry by a fixed value in the event of a 429:

```js
const run = () => fetch('https://sindresorhus.com/unicorn')
  .then((response) => {
    if (response.status === 429) {
      return new Promise((resolve, reject) => setTimeout(() => reject(err), 1000));
    }
  });

pRetry(run, { retries: 5 });
```

Better would be if there were some way to delay by `Math.pow(2, numberOfAttempts)` or something along those lines. Maybe enabling it through an option? Perhaps the caller provides a function that calculates the retry delay?

```js
pRetry(run, { retries: 5, delay: (num) => Math.pow(2, num) * 1000 });
```

**Comment by sindresorhus** [comment]
It should already be doing exponential backoff. Under the hood it uses the [`retry`](https://github.com/tim-kos/node-retry) module.

**Comment by rclark** [comment]
Thanks! I had overlooked [the options indicated in the readme](https://github.com/sindresorhus/p-retry#options).

**Comment by eugene-kim-pipe17** [comment]
@sindresorhus is this behavior documented anywhere? I couldn't find it in the README
