### ISSUE TITLE
onFailedAttempt and promise

### ISSUE THREAD

**Issue by gendronb** [sindresorhus/p-retry#10]
Hi,

Would it be possible to wait until a promise is resolve (or rejected) inside the onFailedAttempt handler before throwing an AbortError? If so, how?

My use case is as follow : I'm fetching data from an API protected by a token, and I'd like to be able to retry the fetch if the token is invalid, but before retrying, I need to try refreshing the token.

1. Try calling API 
2. In case of failure, try refreshing token (wait for promise inside onFailedAttempt)
3. If (2) fails, throw AbortError, otherwise retry (1)

Thanks for your help!

**Comment by acostalima** [comment]
You can wait for a promise within `onFailedAttempt`, but `p-retry` will not wait for it once the handler is called which is probably not what you want.

The following code should work for your use case, although it does not look pretty.

```js
const pRetry = require('p-retry');
const fetch = require('node-fetch');

const refreshToken = async () => await fetch('<refresh-token-url>'); 

const callApi = () => fetch('<api-url>')
	.then(response => {
		if (<invalid token>) {
			return refreshToken();
		}

        if(<bad response>) {
            // throw AbortError or other Error
	    }

		return response;
	})
    .then(response => {
       if (<token refreshed successfully>) {
          throw new Error('Token refresh required');
       }

       if (<token refresh failed>) {
          throw new pRetry.AbortError('Token refresh required');
       }

       return response.json();
    });

pRetry(callApi).then(...);
```

**Comment by acostalima** [comment]
If we make the following change to the code below, `p-retry` will wait for the result of `onFailedAttempt` in case it is asynchronous:

```diff
module.exports = (input, options) => new Promise((resolve, reject) => {
	options = Object.assign({
		onFailedAttempt: () => {},
		retries: 10
	}, options);

	const operation = retry.operation(options);

	operation.attempt(attemptNumber => {
		const attemptsLeft = options.retries - attemptNumber;

		return Promise.resolve(attemptNumber)
			.then(input)
			.then(resolve, error => {
				if (error instanceof AbortError) {
					operation.stop();
					reject(error.originalError);
				} else if (error instanceof TypeError) {
					operation.stop();
					reject(error);
				} else if (operation.retry(error)) {
					error.attemptNumber = attemptNumber;
					error.attemptsLeft = attemptsLeft;
-					options.onFailedAttempt(error);
+                   return options.onFailedAttempt(error);
				} else {
					reject(operation.mainError());
				}
			});
	});
});
```

**Comment by gendronb** [comment]
@acostalima Thanks for you help...

If you run the following code (with the above patch applied), you'll see thats the second api attempt is made BEFORE the refresh token call resolves...

`
import pRetry from "./p-retry.js";

const callApi = (endpoint, param) => {
  console.debug("calling api =>", endpoint);

  // simulate api error on first attempt
  let hasError = param === 1;

  let p = new Promise((resolve, reject) => {
    setTimeout(() => {
      if (hasError) {
        console.warn("api error =>", endpoint);
        reject(new Error(endpoint));
      } else {
        console.debug("api success =>", endpoint);
        resolve(endpoint);
      }
    }, 2000);
  });

  return p;
};

const callEndpoint = async (endpoint, param) => await callApi(endpoint, param);

const retryAsync = async error => {
  console.warn(`attempt ${error.attemptNumber} failed`);
  await callApi("refresh token");
};

const run = i => {
  return callEndpoint("test", i);
};

pRetry(run, {
  retries: 1,
  onFailedAttempt: retryAsync
})
  .then(response => console.info("finished", response))
  .catch(e => console.error("finally failed", e.message));
`

1. calling api => test 
2. api error => test 
3. attempt 1 failed 
4. calling api => refresh token 
5. calling api => test 
6. api success => refresh token 
7. api success => test 
8. finished test

**Comment by acostalima** [comment]
@gendronb sorry for the late reply.

I've figured out what is going on. The problem is that `operation.retry()` is being called before `onFailedAttempt` and it must be called after instead, otherwise the next retry may (or may not) be triggered in parallel, depending on how long `onFailedAttempt` promise takes to settle and the time between retries.

In any case, specifically to your scenario, you most likely need access to the request's response within `onFailedAttempt` to determine whether the token expired, so whatever changes we make to `p-retry` would not help here. 🤔

**Comment by gendronb** [comment]
@acostalima thanks again, will look for another solution..
