### ISSUE TITLE
Rejected promise passed to pRetry raises `UnhandledPromiseRejectionWarning: TypeError`

### ISSUE THREAD

**Issue by AlbertEmil** [sindresorhus/p-retry#18]
API for [`pRetry`](https://github.com/sindresorhus/p-retry#pretryinput-options) states:

> Returns a Promise that is fulfilled when calling input returns a fulfilled promise. If calling input returns a rejected promise, input is called again until the max retries are reached, it then rejects with the last rejection reason.
> 
> It doesn't retry on TypeError as that's a user error.

I am passing a rejected Promise to `pRetry` which then raises a `UnhandledPromiseRejectionWarning: TypeError` due to undefined objects keys of the raised error. According to the error message logged on console, the function `decorateErrorWithCounts` tries to access `attemptNumber` and `retriesLeft` which are not defined for the rejection message the rejected Promise is rejected with. Since the docs address a `TypeError` as an user error explicitly, I am not sure wether this is a problem with the (missing) error handling on my side or inside `p-retry`.

Full traceback is as follows:

```
$ node playground.js 
(node:21184) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'attemptNumber' on string 'rejected the promise'
    at decorateErrorWithCounts (/<projectDirectory>/node_modules/p-retry/index.js:25:22)
    at Promise.resolve.then.then.error (/<projectDirectory>/node_modules/p-retry/index.js:49:5)
(node:21184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:21184) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'attemptNumber' on string 'rejected the promise'
    at decorateErrorWithCounts (/<projectDirectory>/node_modules/p-retry/index.js:25:22)
    at Promise.resolve.then.then.error (/<projectDirectory>/node_modules/p-retry/index.js:52:5)
(node:21184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```

Code snippet to reproduce error:

```
'use strict';

const pRetry = require('p-retry');


const myWrapper = (value) => {
  return () => {
    return new Promise( (resolve, reject) => {
      console.log(value);
      setTimeout(function() {
        // resolve('resolved the promise');
        reject('rejected the promise');
      }, 1000);
    })
  }
}


pRetry(myWrapper(2000),
  {
    retries: 1,
  })
  .then(console.log)
  .catch(console.log)

```

Working on Mac OS 10.10.5 with NodeJS 10.9.0 and p-retry 3.0.0.

**Comment by molant** [comment]
I think this is the same problem as in https://github.com/sindresorhus/p-retry/issues/14#issuecomment-446615891

Try `rejecting` an error instead of a string.

**Comment by AlbertEmil** [comment]
Rejecting and error as @molant stated above, does do the trick. So

`reject('rejected the promise');`

needs to be changed to

`reject(new Error('rejected the promise'));`
