### ISSUE TITLE
Please transpile and npm publish

### ISSUE THREAD

**Issue by InsaneViku** [sindresorhus/p-retry#2]
Hi,

It would be great if you could use babel to transpile ES6 upon npm publish. Currently, I can't utilize your package when using webpack + UglifyJs without having to explicitly transpile your package, being a node_module. I believe it's a common practice for this to be done for any public npm package.

Thanks!

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
