### ISSUE TITLE
Throwing inside async function results in unhandled rejection

### ISSUE THREAD

**Issue by tommedema** [sindresorhus/p-retry#26]
I'm rethrowing an error inside my "run" function and it's not being caught by `p-retry`.

Example:

_app.js_
```
import retry from 'p-retry'
import fetch200 from './fetch200'

const resultResponse = await retry(
  () => { fetch200(url) },
  {
    retries: 10,
    maxRetryTime: 10 * 60  * 1000, // 10 minutes
    onFailedAttempt: (err => console.log('one failed attempt with error: %o', err))
  }
)
```

_fetch200.js_
```
export default async function fetch200() {
  const resp = await fetch.apply(this, arguments)
  if (resp.status < 200 || resp.status >= 300) {
    throw new Error(
      `invalid fetch response status ${resp.status}: ${resp.statusText}`
    )
  }
  return resp
}
```

I've also tried `async () => { fetch200(url) }` instead of `() => { fetch200(url) }` to see if this is [why](https://stackoverflow.com/a/42928209/45974) the exception is not bubbling up, but this doesn't seem to be the case.

Actual behavior:

![Screen Shot 2019-05-14 at 7 19 24 PM](https://user-images.githubusercontent.com/331833/57744223-398c5b00-767d-11e9-8f76-3811a31f1862.png)

**Comment by kevinrambaud** [comment]
You need to return the fetch200 promise such as `() => fech200(url)` or `() => { return fetch200(url) }`, then make sure to have a try/catch around `await retry` call or attach a `.catch` method on it.

**Comment by tommedema** [comment]
Of course, makes sense. The key was the return statement.
