### ISSUE TITLE
Add `onReattempt` option

### ISSUE THREAD

**Issue by kilianc** [sindresorhus/p-retry#3]
it would be nice to have an onError function hooked up to https://github.com/tim-kos/node-retry#retryoperationattemptfn-timeoutops

**Comment by sindresorhus** [comment]
When would it call `onError`? Can you elaborate on what you need and how you would use it?

**Comment by kilianc** [comment]
```js
await retry(() => foo(), {
  onError: (err, attemptNumber, attemptsLeft) => {
    console.error(`Attempt number ${attemptNumber} failed: ${err.message} (${attemptsLeft} left)`)
  }
})
```

**Comment by sindresorhus** [comment]
@kilianc I mean, in what situation would `node-retry` call the `onError` function you supply? From your example, it seems like rejecting the promise might be a better option and including the `attemptNumber` and `attemptsLeft` as properties on the error.

**Comment by SamVerschueren** [comment]
I think what @kilianc wants is a function to be called after every failed attempt so you can show status updates on network requests or something. So if we go for it, it might be better to call the function `onFailure` instead of `onError`.

**Comment by kilianc** [comment]
@SamVerschueren correct. It's mostly for network reattempts. `onFailure` and `onError` sound exactly the same. maybe `onReattempt` ?

**Comment by sindresorhus** [comment]
`onReattempt` 👍 

I assume this would only be called on the second attempt and forward?

**Comment by kilianc** [comment]
`onFailedAttempt` ?

**Comment by acostalima** [comment]
I've just pushed PR #5 to add this feature. 😄

**Comment by monim67** [comment]
I am looking for `onReattempt`/`beforeRetry` functionality, `onFailedAttempt` triggers even when `shouldRetry` returns false and there's going to be no re-attempts. Is there any way I can implement a function that on runs before a guaranteed retry attempt?
