### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by morningdew830** [sindresorhus/p-retry#32]
Hey guys. 
I am getting this error while compiling my project. which is compiled by webpack 3.6.0, babel stuffs are loaded as well.

![image](https://user-images.githubusercontent.com/22661536/68534742-eddc1500-0372-11ea-829b-cfcd325ab128.png)

I don't use the p-retry in my project directly but it's used by @slack/web-api.

Should I install any additional loader to fix this?

Any help?

Thanks in advance!

**Comment by sindresorhus** [comment]
This is not the place to ask Webpack questions. Your Webpack config seems to fail on object spread syntax.
