### ISSUE TITLE
Delayed retry in README leads to unexpected result

### ISSUE THREAD

**Issue by wwahammy** [sindresorhus/p-retry#33]
In the README.md, the following code exists:

```javascript
const pRetry = require('p-retry');
const delay = require('delay');

const run = async () => { ... };

(async () => {
	const result = await pRetry(run, {
		onFailedAttempt: async error => {
			console.log('Waiting for 1 second before retrying');
			await delay(1000);
		}
	});
})();
```

Without knowing the retry module's features, a user may expect that this code would retry the `run` function every 1 second. This is not accurate as the retry module has an [exponential delay function](https://github.com/tim-kos/node-retry/blob/master/lib/retry.js#L54) where, by default, it begins with a 1 second delay in between the first two tries and then multiplies 1 second by 2^(number of tries). The code provided then waits a single second before the retry module's delay between tries executes.

Ideally, this example should be removed since it could lead to confusion for new users of the library.

**Comment by sindresorhus** [comment]
Thanks for commenting. That's a good point. I've improved the example now.

**Comment by jdmarshall** [comment]
I was just trying to write a test and was surprised to find that my retry was taking about 1000 ms longer than I expected.

I don't think trying to add your own delay to the onFailedAttempt() is the correct solution here. I think documenting the options pass-through to retry is the correct strategy. For instance:

`pRetry(myFunction, { retries: 2, minTimeout: timeout, factor: 1 })`

**Comment by jdmarshall** [comment]
Additionally, because the retry module is not using arrow functions, it ends up rebinding 'this', which I didn't notice in my initial implementation, and so my delay function was getting undefined as an argument.

The way I'm suggesting avoids that problem, but you might want to work that into any other examples, if for no other reason to signal to people "hey this bit is tricky".
