### ISSUE TITLE
Are retries nestable?

### ISSUE THREAD

**Issue by ToddHoff** [sindresorhus/p-retry#34]
Is there any reason a retry loop can't be nested inside another retry loop?

thanks

**Comment by sindresorhus** [comment]
You can of course nest them, but are you expecting any special behavior? Hard to answer without more context.

**Comment by ToddHoff** [comment]
Nothing special, it's a retry on a connection wrapped by a parsing retry. it's just that often things aren't composable. Good work. Thanks.

**Comment by acostalima** [comment]
@sindresorhus I think this can be closed.
