### ISSUE TITLE
`TypeError: options.onFailedAttempt is not a function` when onFailedAttempt is null or undefined

### ISSUE THREAD

**Issue by gabegorelick** [sindresorhus/p-retry#36]
A default is provided for the `onFailedAttempt` option, but only if `onFailedAttempt` is not in the `options` object Relevant code: https://github.com/sindresorhus/p-retry/blob/0608b649aff0ad6836e8a11884385ee29d5eb244/index.js#L31-L35

This means that if `options.onFailedAttempt` is `null` or `undefined`, you get a `TypeError`  when attempting to invoke it. But in passing `null` or `undefined`, the caller probably wanted to use the default `onFailedAttempt` handler (I know that's what I want).

This is obviously easy to workaround once you know about it, but does seem like a gotcha.

**Comment by sindresorhus** [comment]
I agree we should handle the `undefined` case, but not `null`. We could use destructuring with defaults instead of object spreading.

**Comment by fungairino** [comment]
This is an old issue, but it is still relevant and impacts other options like `shouldRetry` as well. We just ran into this issue when passing in an undefined value for it.

`TypeError: options.shouldRetry is not a function`
