### ISSUE TITLE
exclude fetchApi "Failed to fetch" from ignores 

### ISSUE THREAD

**Issue by oreporan** [sindresorhus/p-retry#37]
Currently, as the API states, you discard instance of `TypeError`, however, the fetchApi `Failed to fetch` exception is of type `TypeError`.
One of the common reasons that this error occurs can be network connection issues.
Is it possible to include this exception? 
The main reason I want to add a retry mechanism is incase the user had a bad internet connection during that second where the request was going out

From [Fetch documentation](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch):

> A fetch() promise will reject with a TypeError when a network error is encountered or CORS is misconfigured on the server-side

Current workaround:

```js
 pRetry(async () => {
        try {
            return await fetchRequest()
        } catch (error) {
            if (error instanceof TypeError && error.message === 'Failed to fetch') {
                throw new Error('Failed to fetch')
            }
            throw error;
        }
    }, {
        retries: 2,
        onFailedAttempt,
    });
```

Thanks

**Comment by sindresorhus** [comment]
Who thought it was a good idea for Fetch to throw a `TypeError` on network errors...

---

Slightly relevant issue: https://github.com/whatwg/fetch/issues/526

**Comment by oreporan** [comment]
I'm also happy to put a PR in place

**Comment by sindresorhus** [comment]
Yes. PR welcome :)

**Comment by chenliu0831** [comment]
+1, this is a bit unexpected when people use retry to mitigate network errors from fetch
