### ISSUE TITLE
require/import('p-retry') example for 5.0.0

### ISSUE THREAD

**Issue by fcpunk** [sindresorhus/p-retry#55]
Any example of CommonJS import for 5.0.0 would be appreciated. Migrating to ES6 imports is not something everyone can afford at the moment due to the inability to use both CommonJS and ES6 imports in the same project.
import('p-retry') fails.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c See item `2.`.
