### ISSUE TITLE
Package p-retry has been ignored because it contains invalid configuration

### ISSUE THREAD

**Issue by KrisLau** [sindresorhus/p-retry#56]
Getting this error whenever I try to run my app:
`Package p-retry has been ignored because it contains invalid configuration`

I've tried `yarn remove p-retry` then re-adding it but that didn't seem to work either. I noticed that the package is missing from my node_modules when  to search for it in my directory however alt-clicking directs me to a file that is supposedly in the `node_modules` directory. I can find it in my file explorer but not in intellij basically.

**Comment by sindresorhus** [comment]
This is a problem with the tool you're using and not this package. The tool you're using probably doesn't support ESM.

**Comment by KrisLau** [comment]
@sindresorhus I'm using react native and I believe it supports ESM no?
