### ISSUE TITLE
Is there a way to exclude certain errors?

### ISSUE THREAD

**Issue by dsego** [sindresorhus/p-retry#6]
I would want it to keep trying when a `NetworkError` is thrown, but if it's a `PermissionError` it should abort and re-throw the exception.

**Comment by acostalima** [comment]
You can [wrap](https://github.com/sindresorhus/p-retry#pretryaborterrormessageerror) `PermissionError` in `AbortError`. Would that be enough for your use case?

**Comment by dsego** [comment]
Sure.

**Comment by acostalima** [comment]
I guess you can close the issue then. :)
