### ISSUE TITLE
Backport AbortController to 4.x

### ISSUE THREAD

**Issue by micaelmbagira** [sindresorhus/p-retry#63]
Is it possible to merge the [AbortController feature](https://github.com/sindresorhus/p-retry/commit/352d62adf0420782c97068a4c0f9c2927cbc938b) in 4.x? Unfortunately, ESM is not supported everywhere (e.g. Jest supports it but with a lot of caveats -- mocks are not working for example) and the cancellation feature is quite useful.
I am happy to open a PR but there's no branch for 4.x.

**Comment by sindresorhus** [comment]
I don't intend to backport it. It's just too much work if I say yes to backport everything. However, you can import it using `await import('p-retry')` which does work in CommonJS.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
