### ISSUE TITLE
No longer useable via TypeScript due to @types/retry dependency release

### ISSUE THREAD

**Issue by ericbarch** [sindresorhus/p-retry#64]
A few hours ago, a new version of @types/retry was published. This changed the definition of `OperationOptions`, which this package depends upon.

Whenever attempting to use p-retry, I now receive the following error:

`npm ERR! ../../p-retry/index.d.ts(20,31): error TS2312: An interface can only extend an object type or intersection of object types with statically known members.`

Not sure if a code change or pinning a specific version of `retry` is the way to go here.

**Comment by ericbarch** [comment]
The referenced change can be found here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59861/files#diff-a900405590266ddb7fa8ba411eadf3240d0c7630a51adc7432207c4e7c198a20

**Comment by jasonflorentino** [comment]
I was just running into the same thing.
Fixing the previous version of the retry types seemed to be a good fix for now...
```
# package.json / devDependencies

"@types/retry": "0.12.1",
```

**Comment by justinpincar** [comment]
Unless you have `noEmitOnError`set you can also just ignore the type error until it's fixed: `tsc || true`

**Comment by bugb** [comment]
Hi team,
Any updates on this issue? We are stuck at many build because of the error.

**Comment by sindresorhus** [comment]
I was sleeping. Will do a new release asap.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/p-retry/releases/tag/v5.1.1

**Comment by hitotito** [comment]
Does `p-retry@"4.6.1`, also need to be fix for version 4.x.x?

**Comment by bugb** [comment]
I got error when using v4 too 
@sindresorhus any fix for v4 would be great!!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/p-retry/releases/tag/v4.6.2

**Comment by bugb** [comment]
@sindresorhus let me check it, thank you a lot!

**Comment by bugb** [comment]
@sindresorhus it works, thank for your hard work, I appreciate it!
