### ISSUE TITLE
Ability to customize whether an error should be retried

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/p-retry#70]
See: https://github.com/sindresorhus/p-retry/pull/67

**Comment by xmedeko** [comment]
I like solution of https://github.com/vercel/async-retry - the `input` function callback has a parametr `bail` (or `reject`) which rejects the Promise immediately. All other errors are considered to do retry.

**Comment by sindresorhus** [comment]
I agree. It's a better solution.

Another one would be to not pass a parameter, but instead have `pRetry.BailError` that you could throw and then it would not retry.

**Comment by sindresorhus** [comment]
Actually, we already support `AbortController`, so this is already possible, although a bit more verbose.
