### ISSUE TITLE
Retry undici network errors on 4.x

### ISSUE THREAD

**Issue by pebo** [sindresorhus/p-retry#72]
Could we please backport https://github.com/sindresorhus/p-retry/pull/68 to p-retry 4.x to support retries of undici network errors?

**Comment by sindresorhus** [comment]
I don't plan to backport to v4.

**Comment by pebo** [comment]
> I don't plan to backport to v4.

I understand that v4 isn't top prio but the effect of this issue is that network errors, e.g. ECONN_RESET, aren't retried on modern node versions. We'd love to move to ESM but that journey will take some time. Is there a workaround for this on `p-retry 4.62`?
