### ISSUE TITLE
Selecting appropriate version

### ISSUE THREAD

**Issue by pdulapalli** [sindresorhus/p-retry#8]
Hello,

I know you no longer currently support Node v4.x.x, but would you please point me to the most recent release version which supports Node v4.x.x?

(Out of curiosity, which features have you added that break compatibility with Node v4.x.x, but work with Node version 6?)

Thank you!

**Comment by sindresorhus** [comment]
The information you seek is readily available in the commit history: https://github.com/sindresorhus/p-retry/commits/master
